College_Attendance/Controllers/AdminHomeController.cs
using College_Attendance.Models;
using College_Attendance.Models.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;

namespace College_Attendance.Controllers
{
    public class AdminHomeController : Controller
    {
        private readonly ILogger<AdminHomeController> _logger;
        private readonly IAttendanceData _attendanceData;

        public AdminHomeController(ILogger<AdminHomeController> logger, IAttendanceData attendanceData)
        {
            _logger = logger;
            _attendanceData = attendanceData;
        }

        [Authorize]
        public IActionResult Index()
        {
            var allAttendance = _attendanceData.GetAttendance();

            // Calculate average attendance per day of the week
            var averageAttendancePerDay = allAttendance
                .GroupBy(a => a.Date.DayOfWeek)
                .Select(g => (int)((double)g.Count(a => a.IsPresent) / g.Count() * 100)) // Ratio of present to total
                .ToList();

            // Calculate average attendance per subject
            var averageAttendancePerSubject = allAttendance
                .GroupBy(a => a.SubjectId)
                .Select(g => (int)((double)g.Count(a => a.IsPresent) / g.Count() * 100)) // Ratio of present to total
                .ToList();

            var subjects = allAttendance
                .GroupBy(a => a.SubjectId)
                .Select(g => _attendanceData.GetSubjectNameByID(g.Key))
                .ToList();

            var viewModel = new AttendanceSummaryViewModel
            {
                AverageAttendancePerDay = averageAttendancePerDay,
                AverageAttendancePerSubject = averageAttendancePerSubject,
                Subjects = subjects
            };

            return View(viewModel);
        }

       
    }
}

College_Attendance/Controllers/AttendanceController.cs
using College_Attendance.Data;
using College_Attendance.Models;
using College_Attendance.Models.Class;
using College_Attendance.Models.Interface;
using Microsoft.AspNetCore.Mvc;

namespace College_Attendance.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly IAttendanceData _attendanceData;
        private readonly ApplicationDbContext _context;

        public AttendanceController(IAttendanceData attendanceData, ApplicationDbContext context)
        {
            _attendanceData = attendanceData;
            _context = context;
        }

        // GET: Attendance/MarkAttendance
        [HttpGet]
        public IActionResult MarkAttendance()
        {
            var model = new MarkAttendanceViewModel
            {
                Date = DateTime.Now,
                Subjects = _context.Subjects.ToList(),
                Students = _context.Students
                    .Select(s => new MarkAttendanceViewModel.StudentAttendance
                    {
                        StudentId = s.StudentId,
                        StudentName = s.FirstName + " " + s.LastName,
                        IsPresent = true
                    })
                    .ToList()
            };

            return View(model);
        }

        // POST: Attendance/MarkAttendance
        [HttpPost]
        public IActionResult MarkAttendance(MarkAttendanceViewModel model)
        {
            foreach (var student in model.Students)
            {
                var existingAttendance = _context.Attendances
                    .FirstOrDefault(a => a.StudentId == student.StudentId && a.SubjectId == model.SubjectId && a.Date.Date == model.Date.Date);

                if (existingAttendance != null)
                {
                    existingAttendance.IsPresent = student.IsPresent;
                    _context.Update(existingAttendance);
                }
                else
                {
                    var attendance = new Attendance
                    {
                        StudentId = student.StudentId,
                        SubjectId = model.SubjectId,
                        Date = model.Date,
                        IsPresent = student.IsPresent
                    };
                    _context.Add(attendance);
                }
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        // GET: /Attendance/FetchAttendance
        public IActionResult FetchAttendance()
        {
            var model = new MarkAttendanceViewModel
            {
                Subjects = _context.Subjects.ToList(),
                
            };
            model.Students = _context.Students
                    .Select(s => new MarkAttendanceViewModel.StudentAttendance
                    {
                        StudentId = s.StudentId,
                        StudentName = s.FirstName + " " + s.LastName,
                        IsPresent = true
                    })
                    .ToList();

            return View(model);
        }

        // POST: /Attendance/FetchAttendance
        [HttpPost]
        public IActionResult FetchAttendance(MarkAttendanceViewModel model)
        {
            // Fetch attendance records based on the selected date and subject
            var attendanceRecords = _context.Attendances
                .Where(a => a.Date.Date == model.Date)
                .Select(a => new AttendanceRecordViewModel
                {
                    Date = a.Date,
                    SubjectName = _context.Subjects
                        .Where(s => s.SubjectId == a.SubjectId)
                        .Select(s => s.SubjectName)
                        .FirstOrDefault(),
                    StudentName = _context.Students
                        .Where(s => s.StudentId == a.StudentId)
                        .Select(s => s.FirstName + " " + s.LastName)
                        .FirstOrDefault(),
                    IsPresent = a.IsPresent
                })
                .ToList();

            // Pass the data to the AttendanceRecords view
            return View("AttendanceRecords", attendanceRecords);
        }
        [HttpPost]
        public IActionResult FetchAttendanceOnSubject(MarkAttendanceViewModel model)
        {
            // Fetch attendance records based on the selected date and subject
            var attendanceRecords = _context.Attendances
                .Where(a => a.SubjectId == model.SubjectId)
                .Select(a => new AttendanceRecordViewModel
                {
                    Date = a.Date,
                    SubjectName = _context.Subjects
                        .Where(s => s.SubjectId == a.SubjectId)
                        .Select(s => s.SubjectName)
                        .FirstOrDefault(),
                    StudentName = _context.Students
                        .Where(s => s.StudentId == a.StudentId)
                        .Select(s => s.FirstName + " " + s.LastName)
                        .FirstOrDefault(),
                    IsPresent = a.IsPresent
                })
                .ToList();

            // Pass the data to the AttendanceRecords view
            return View("AttendanceRecords", attendanceRecords);
        }

        [HttpPost]
        public IActionResult FetchAttendanceOnStudent(MarkAttendanceViewModel model)
        {
            // Fetch attendance records based on the selected date and subject
            int sid = model.Students[0].StudentId;
            var attendanceRecords = _context.Attendances
                .Where(a => a.StudentId == sid)
                .Select(a => new AttendanceRecordViewModel
                {
                    Date = a.Date,
                    SubjectName = _context.Subjects
                        .Where(s => s.SubjectId == a.SubjectId)
                        .Select(s => s.SubjectName)
                        .FirstOrDefault(),
                    StudentName = _context.Students
                        .Where(s => s.StudentId == a.StudentId)
                        .Select(s => s.FirstName + " " + s.LastName)
                        .FirstOrDefault(),
                    IsPresent = a.IsPresent
                })
                .ToList();

            // Pass the data to the AttendanceRecords view
            return View("AttendanceRecords", attendanceRecords);
        }
    }
}

College_Attendance/Controllers/AttendanceEditController.cs
using College_Attendance.Data;
using College_Attendance.Models;
using College_Attendance.Models.Class;
using College_Attendance.Models.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace College_Attendance.Controllers
{
    public class AttendanceEditController : Controller
    {
        private readonly IAttendanceData _attendanceData;

        public AttendanceEditController(IAttendanceData attendanceData)
        {
            _attendanceData = attendanceData;
        }

        // Action to display the form to select a date
        public IActionResult ListDates(bool? isreadonly = false)
        {
            var dates = _attendanceData.GetAttendance()
                                .Select(a => a.Date.Date)
                                .Distinct()
                                .ToList();
            TempData["IsReadOnly"] = isreadonly;
            return View(dates);
        }

        // Action to list all unique subjects for a selected date
        public IActionResult SelectSubjects(DateTime date)
        {
            var attendance = _attendanceData.GetAttendanceByDate(date);
            var subjectIds = attendance.Select(a => a.SubjectId).Distinct().ToList();
            var subjects = subjectIds.Select(subjectId => new Subject
            {
                SubjectId = subjectId,
                SubjectName = _attendanceData.GetSubjectNameByID(subjectId)
            }).ToList();

            var viewModel = new MarkAttendanceViewModel
            {
                Date = date,
                Subjects = subjects
            };

            return View(viewModel);
        }

        // Action to display students for attendance editing
        public IActionResult EditAttendance(DateTime date, int subjectId,string subjectName )
        {
            var attendance = _attendanceData.GetAttendanceForDateAndTime(date, subjectId);
            var students = attendance.Select(a => new MarkAttendanceViewModel.StudentAttendance
            {
                AttendanceId = a.AttendanceId,
                StudentId = a.StudentId,
                StudentName = _attendanceData.GetStudentNameByID(a.StudentId),
                IsPresent = a.IsPresent
            }).ToList();

            List<Subject> SubjectList=new List<Subject>();
            SubjectList.Add(new Subject { SubjectName = _attendanceData.GetSubjectNameByID(subjectId) });
            var viewModel = new MarkAttendanceViewModel
            {
                Date = date,
                SubjectId = subjectId,
                Subjects=SubjectList,
                Students = students
            };

            return View(viewModel);
        }

        // Action to save the edited attendance
        [HttpPost]
        public IActionResult SaveAttendance(MarkAttendanceViewModel model)
        {
            foreach (var student in model.Students)
            {
                _attendanceData.EditAttendance(student.AttendanceId, student.IsPresent);
            }

            return RedirectToAction("Index","AdminHome");
        }
    }
}

College_Attendance/Views/AdminHome/Index.cshtml
@model College_Attendance.Models.AttendanceSummaryViewModel

@{
    ViewData["Title"] = "Home Page";
}

<body style=" background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="d-flex flex-column justify-content-center align-items-center ">
        <div class="text-center mb-4">
            <h1 class="display-4">Welcome</h1>
        </div>

        <div class="container">
            <div class="row justify-content-center">
                <!-- Card for Edit Attendance -->
                <div class="col-md-4 mb-3">
                    <div class="card bg-primary text-white hover-card">
                        <div class="card-body">
                            <h5 class="card-title">Record Attendance</h5>
                            <p class="card-text">add attendance for new sessions.</p>
                            <a class="btn btn-light rounded-pill hover-button" asp-area="" asp-controller="Attendance" asp-action="MarkAttendance">Mark Attendance</a>
                        </div>
                    </div>
                </div>


                <div class="col-md-4 mb-3">
                    <div class="card bg-primary text-white hover-card">
                        <div class="card-body">
                            <h5 class="card-title">Edit Attendance</h5>
                            <p class="card-text"> Based on the Subject,Date or Student</p>
                            <a class="btn btn-light rounded-pill hover-button" asp-area="" asp-controller="AttendanceEdit" asp-action="ListDates">View Attendance</a>
                        </div>
                    </div>
                </div>




            </div>
        </div>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <canvas id="averageAttendancePerDayChart"></canvas>
                </div>
                <div class="col-md-6">
                    <canvas id="averageAttendancePerSubjectChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        // Chart for Average Attendance per Day
        var ctx1 = document.getElementById('averageAttendancePerDayChart').getContext('2d');
        var averageAttendancePerDayChart = new Chart(ctx1, {
            type:"bar",
            data: {
                labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
                datasets: [{
                    label: 'Average Attendance (%)',
                    data: @Html.Raw(Json.Serialize(Model.AverageAttendancePerDay)),
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100
                    }
                }
            }
        });

        // Chart for Average Attendance per Subject
        var ctx2 = document.getElementById('averageAttendancePerSubjectChart').getContext('2d');
        var averageAttendancePerSubjectChart = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: @Html.Raw(Json.Serialize(Model.Subjects)),
                datasets: [{
                    label: 'Average Attendance (%)',
                    data: @Html.Raw(Json.Serialize(Model.AverageAttendancePerSubject)),
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100
                    }
                }
            }
        });
    </script>
}